apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-config
  namespace: agentgateway
data:
  config.yaml: |
    binds:
      - port: 8080
        listeners:
          - routes:
              - backends:
                  - llm:
                      providers:
                        - name: openai
                          type: openai
                          apiKeyEnv: OPENAI_API_KEY
                        - name: groq
                          type: openaiCompatible
                          apiBase: https://api.groq.com/openai/v1
                          apiKeyEnv: GROQ_API_KEY
                      model: groq/llama-3.1-8b-instant
