apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ .Values.global.destination.project }}
  source:
    repoURL: https://github.com/Azeezat-git/agentgateway-lab.git
    targetRevision: main
    path: {{ .Values.paths.agentgatewayManifests }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.namespaces.agentgateway }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
