global:
  destination:
    server: https://172.31.45.157:33893
    project: default

gatewayApiCrds:
  # Path is repo-root-relative; you already vendored the CRDs here
  path: gateway-api-crds

kgatewayCrds:
  repoURL: oci://cr.kgateway.dev
  chart: kgateway-dev/charts/kgateway-crds
  targetRevision: v2.2.0
  namespace: kgateway-system

kgateway:
  repoURL: oci://cr.kgateway.dev
  chart: kgateway-dev/charts/kgateway
  targetRevision: v2.2.0
  namespace: kgateway-system
  values:
    agentgateway:
      enabled: true
      # mount OPENAI_API_KEY/GROQ_API_KEY from kgateway-system/agentgateway-secrets
      proxy:
        extraEnvFrom:
          - secretRef:
              name: agentgateway-secrets
    controller:
      image:
        pullPolicy: Always

gatewayManifest:
  # Path holding your Gateway YAML (agentgateway-gateway.yaml)
  path: manifests
