apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway
  namespace: agentgateway
  labels:
    app: agentgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentgateway
  template:
    metadata:
      labels:
        app: agentgateway
    spec:
      containers:
        - name: agentgateway
          image: alpine:3.20
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: agentgateway-secrets
          command: ["/bin/sh","-c"]
          args:
            - >
              set -e;
              apk add --no-cache curl bash;
              curl -sSfL https://raw.githubusercontent.com/agentgateway/agentgateway/refs/heads/main/common/scripts/get-agentgateway | bash;
              /usr/local/bin/agentgateway -f /etc/agentgateway/config.yaml
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: cfg
              mountPath: /etc/agentgateway
      volumes:
        - name: cfg
          configMap:
            name: agentgateway-config
