apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    app: agent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: agent
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
